


version: "2"

services:
  mltoys:
    image: ml_toys
    volumes:
      - ".:/notebook"
    restart: always
    ports:
      - "8888:8888"

  flask_serv:
    image: tiangolo/uwsgi-nginx-flask:python3.6-alpine3.7
    ports:
      - "80:80"
      - "443:443"
    restart: always 
    volumes:
      - "./app:/app"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=0
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"

